chore(docs): Add documentation for createNextRouteHandler config
pingdotgg/uploadthing pull request #271
Opened 2023-08-18 20:02 UTC by markflorkowski

2023-08-21 23:47 UTC, t3dotgg commented on docs/src/pages/api-reference/next.mdx
> +This configuration is entirely optional, but may be useful if you would like to
Maybe note the env variable we use by default?

2023-08-27 08:41 UTC, juliusmarminge requested changes

2023-08-27 08:41 UTC, juliusmarminge commented on docs/src/pages/api-reference/next.mdx
> +  config: {
we have a `callbackUrl` option too: https://github.com/pingdotgg/uploadthing/blob/9b1e2b722f5a80d5bb6205491e753998e4420d6b/packages/uploadthing/src/internal/handler.ts#L130C3-L130C26

2023-08-27 08:41 UTC, juliusmarminge commented on docs/src/pages/api-reference/next.mdx
should probably note down that this works for the `createNextPageApiHandler` too

2023-08-28 23:16 UTC, merged