ADDED issue template for bug report
pingdotgg/uploadthing pull request #43
Opened 2023-05-11 14:26 UTC by Caketime

ADDED basic code of conduct
<img width="956" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/e140756b-c990-4005-be53-21d3cfe287f7">
<img width="923" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/7b31f974-9908-451c-85b2-8ec2598496dd">
<img width="1036" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/a71f360c-9aba-4353-93f6-f2fc628763b4">

2023-05-14 09:19 UTC, juliusmarminge commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +labels: ["bug"]
unconfirmed_bug is probably more used and then we switch to bug once its reproduced

Thats how we do in t3-oss and trpc atleast

2023-05-14 11:30 UTC, Caketime commented
Force pushed an update so it stays a single commit.

Changes: Label "bug" -> "uncofirmed_bug"

2023-05-15 05:10 UTC, markflorkowski requested changes
I'd also like to have "Reproduction Repository" and "Reproduction Steps" fields. They can be optional. 

Otherwise looks good!

2023-05-15 06:08 UTC, Caketime commented
- Added optional "Reproduction Repository" and "Reproduction Steps" fields

- Updated the "what did you expect to happen" description from "What did you expect to happen?" to "Please describe what you expected to happen."

2023-05-15 07:25 UTC, markflorkowski approved these changes

2023-05-15 07:25 UTC, merged